/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CardRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cards"
      | "getCardsByRarity"
      | "getRandomCardOfRarity"
      | "getRarity"
      | "isRegistered"
      | "owner"
      | "rarityPoolSize"
      | "registerCards"
      | "renounceOwnership"
      | "totalCards"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CardRegistered" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "cards", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getCardsByRarity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomCardOfRarity",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRarity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rarityPoolSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCards",
    values: [BigNumberish[], BigNumberish[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "cards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCardsByRarity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomCardOfRarity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRarity", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rarityPoolSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalCards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CardRegisteredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    rarity: BigNumberish,
    anime: BigNumberish,
    maxSupply: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    rarity: bigint,
    anime: bigint,
    maxSupply: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    rarity: bigint;
    anime: bigint;
    maxSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CardRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CardRegistry;
  waitForDeployment(): Promise<this>;

  interface: CardRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cards: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        rarity: bigint;
        anime: bigint;
        maxSupply: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  getCardsByRarity: TypedContractMethod<
    [rarity: BigNumberish],
    [bigint[]],
    "view"
  >;

  getRandomCardOfRarity: TypedContractMethod<
    [rarity: BigNumberish, seed: BigNumberish, nonce: BigNumberish],
    [bigint],
    "view"
  >;

  getRarity: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  isRegistered: TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  rarityPoolSize: TypedContractMethod<[rarity: BigNumberish], [bigint], "view">;

  registerCards: TypedContractMethod<
    [
      tokenIds: BigNumberish[],
      rarities: BigNumberish[],
      animes: BigNumberish[],
      maxSupplies: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalCards: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cards"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        rarity: bigint;
        anime: bigint;
        maxSupply: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCardsByRarity"
  ): TypedContractMethod<[rarity: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRandomCardOfRarity"
  ): TypedContractMethod<
    [rarity: BigNumberish, seed: BigNumberish, nonce: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRarity"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rarityPoolSize"
  ): TypedContractMethod<[rarity: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerCards"
  ): TypedContractMethod<
    [
      tokenIds: BigNumberish[],
      rarities: BigNumberish[],
      animes: BigNumberish[],
      maxSupplies: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalCards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CardRegistered"
  ): TypedContractEvent<
    CardRegisteredEvent.InputTuple,
    CardRegisteredEvent.OutputTuple,
    CardRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CardRegistered(uint256,uint8,uint8,uint256)": TypedContractEvent<
      CardRegisteredEvent.InputTuple,
      CardRegisteredEvent.OutputTuple,
      CardRegisteredEvent.OutputObject
    >;
    CardRegistered: TypedContractEvent<
      CardRegisteredEvent.InputTuple,
      CardRegisteredEvent.OutputTuple,
      CardRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
