/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GachaPackInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "effectiveMythicThreshold"
      | "getPityCount"
      | "nft"
      | "openPremiumPack"
      | "openStandardPack"
      | "openUltraPack"
      | "owner"
      | "packConfigs"
      | "packsWithoutMythic"
      | "registry"
      | "renounceOwnership"
      | "setPackPrice"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CardMinted"
      | "OwnershipTransferred"
      | "PackOpened"
      | "PackPriceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "effectiveMythicThreshold",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPityCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nft", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "openPremiumPack",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openStandardPack",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openUltraPack",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "packConfigs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "packsWithoutMythic",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPackPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "effectiveMythicThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPityCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openPremiumPack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openStandardPack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openUltraPack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "packConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "packsWithoutMythic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPackPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CardMintedEvent {
  export type InputTuple = [
    player: AddressLike,
    tokenId: BigNumberish,
    rarity: BigNumberish
  ];
  export type OutputTuple = [player: string, tokenId: bigint, rarity: bigint];
  export interface OutputObject {
    player: string;
    tokenId: bigint;
    rarity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackOpenedEvent {
  export type InputTuple = [
    player: AddressLike,
    packType: BigNumberish,
    tokenIds: BigNumberish[]
  ];
  export type OutputTuple = [
    player: string,
    packType: bigint,
    tokenIds: bigint[]
  ];
  export interface OutputObject {
    player: string;
    packType: bigint;
    tokenIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackPriceUpdatedEvent {
  export type InputTuple = [packType: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [packType: bigint, newPrice: bigint];
  export interface OutputObject {
    packType: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GachaPack extends BaseContract {
  connect(runner?: ContractRunner | null): GachaPack;
  waitForDeployment(): Promise<this>;

  interface: GachaPackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  effectiveMythicThreshold: TypedContractMethod<
    [player: AddressLike],
    [bigint],
    "view"
  >;

  getPityCount: TypedContractMethod<[player: AddressLike], [bigint], "view">;

  nft: TypedContractMethod<[], [string], "view">;

  openPremiumPack: TypedContractMethod<[], [void], "payable">;

  openStandardPack: TypedContractMethod<[], [void], "payable">;

  openUltraPack: TypedContractMethod<[], [void], "payable">;

  owner: TypedContractMethod<[], [string], "view">;

  packConfigs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        price: bigint;
        size: bigint;
        minRare: bigint;
        minLegendary: boolean;
      }
    ],
    "view"
  >;

  packsWithoutMythic: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPackPrice: TypedContractMethod<
    [packType: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "effectiveMythicThreshold"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPityCount"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nft"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "openPremiumPack"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "openStandardPack"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "openUltraPack"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "packConfigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        price: bigint;
        size: bigint;
        minRare: bigint;
        minLegendary: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "packsWithoutMythic"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPackPrice"
  ): TypedContractMethod<
    [packType: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CardMinted"
  ): TypedContractEvent<
    CardMintedEvent.InputTuple,
    CardMintedEvent.OutputTuple,
    CardMintedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PackOpened"
  ): TypedContractEvent<
    PackOpenedEvent.InputTuple,
    PackOpenedEvent.OutputTuple,
    PackOpenedEvent.OutputObject
  >;
  getEvent(
    key: "PackPriceUpdated"
  ): TypedContractEvent<
    PackPriceUpdatedEvent.InputTuple,
    PackPriceUpdatedEvent.OutputTuple,
    PackPriceUpdatedEvent.OutputObject
  >;

  filters: {
    "CardMinted(address,uint256,uint8)": TypedContractEvent<
      CardMintedEvent.InputTuple,
      CardMintedEvent.OutputTuple,
      CardMintedEvent.OutputObject
    >;
    CardMinted: TypedContractEvent<
      CardMintedEvent.InputTuple,
      CardMintedEvent.OutputTuple,
      CardMintedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PackOpened(address,uint8,uint256[])": TypedContractEvent<
      PackOpenedEvent.InputTuple,
      PackOpenedEvent.OutputTuple,
      PackOpenedEvent.OutputObject
    >;
    PackOpened: TypedContractEvent<
      PackOpenedEvent.InputTuple,
      PackOpenedEvent.OutputTuple,
      PackOpenedEvent.OutputObject
    >;

    "PackPriceUpdated(uint8,uint256)": TypedContractEvent<
      PackPriceUpdatedEvent.InputTuple,
      PackPriceUpdatedEvent.OutputTuple,
      PackPriceUpdatedEvent.OutputObject
    >;
    PackPriceUpdated: TypedContractEvent<
      PackPriceUpdatedEvent.InputTuple,
      PackPriceUpdatedEvent.OutputTuple,
      PackPriceUpdatedEvent.OutputObject
    >;
  };
}
